name: 'Test Local Action'

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'E4-Python/package-test'
      branch:
        description: 'Branch'
        required: true
        default: 'master'
      package-name:
        description: 'Package Name'
        required: true

jobs:
  test-local-action:
    runs-on: ubuntu-latest
    env:
      TARGET_REPOSITORY_PATH: 'target-repository'

    steps:
      - name: 'Checkout local repository'
        uses: actions/checkout@v4
        with:
          path: 'local-repository'
      - name: 'Checkout target repository'
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          path: ${{ env.TARGET_REPOSITORY_PATH }}
          token: ${{ secrets.ORGANIZATION_TOKEN }}
      - name: 'Set up python'
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: 'Upgrade pip'
        run: python -m pip install --upgrade pip
      - name: 'Test local action'
        uses: ./local-repository/
        with:
          target-repository-path: ${{ env.TARGET_REPOSITORY_PATH }}
          package-name: ${{ inputs.package-name }}
